name: Release Actions
on:
  workflow_dispatch:
  push:
    branches: [workflow-concurrent-jobs]
    tags: ["v[0-9].[0-9]+.[0-9]+-*"]

env:
  SET_ENV: ""
jobs:
  setUpEnv:
    runs-on: [macOS-latest]

    outputs:
      currentEnv: ${{steps.step1.outputs.env}}

    steps:
      # - uses: actions/checkout@v2

      # - uses: actions/setup-node@v2
      #   with:
      #     cache: "yarn"

      # - name: yarn install
      #   run: yarn install

      - name: Check Tag
        id: get_tag_version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - if: (!endsWith(steps.get_tag_version.outputs.tag,'-dev') && !endsWith(steps.get_tag_version.outputs.tag,'-stag') && !endsWith(steps.get_tag_version.outputs.tag,'-qa') && !endsWith(steps.get_tag_version.outputs.tag,'-prod') )
        run: exit 1

      - if: contains(steps.get_tag_version.outputs.tag,'dev')
        run: echo "::set-output name=env::env:dev"
        env:
          SET_ENV: env:dev

      - if: contains(steps.get_tag_version.outputs.tag,'qa')
        run: echo "::set-output name=env::env:qa"
        env:
          SET_ENV: env:qa

      - if: contains(steps.get_tag_version.outputs.tag,'stag')
        run: echo "::set-output name=env::env:stag"
        env:
          SET_ENV: env:stag

      - if: contains(steps.get_tag_version.outputs.tag,'prod')
        run: echo "::set-output name=env::env:prod"
        env:
          SET_ENV: env:prod

  createiOSRelease:
    runs-on: [macOS-latest]
    needs: [setUpEnv]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"

      - name: yarn install
        run: yarn install

      - name: Set Env
        # run: echo ${{needs.setUpEnv.outputs.currentEnv}}
        run: |
          yarn ${{env.SET_ENV}}
          echo ${{env.SET_ENV}}

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.BUILD_CERTIFICATE_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Make iOS Release
        run: yarn releaseIOS

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: builds/ipa/SEMANTIC-DEMO.ipa

  createAndroidRelease:
    runs-on: [macOS-latest]
    needs: [setUpEnv]
    steps:
      - name: Set Env
        # run: yarn ${{needs.setUpEnv.outputs.currentEnv}}
        run: |
          yarn ${{needs.setUpEnv.outputs.currentEnv}}
          echo ${{needs.setUpEnv.outputs.currentEnv}}

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"

      - name: yarn install
        run: yarn install

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Android Release
        run: yarn releaseApk

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/

  publishRelease:
    runs-on: [macOS-latest]
    needs: [createAndroidRelease]
    steps:
      - name: Download artifact android
        uses: actions/download-artifact@v2
        with:
          name: release-apk

      # - name: Download artifact from ios
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: release-ipa

      - name: Set apk and ipa as output parameters
        id: set_outputs
        run: |
          echo "::set-output name=release-apk::$(<release-apk/android/app/build/outputs/apk/release/)"
          # echo "::set-output name=release-ipa::$(<release-ipa/builds/**/*.ipa)"

      - name: Show the values of the outputs
        run: |
          # using the syntax steps.<step_id>.outputs.<output_name> to access the output parameters
          echo "status_job1 = ${{ steps.set_outputs.outputs.release-apk }}"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{steps.get_tag_version.outputs.tag}}
          files: |
            ${{ steps.set_outputs.outputs.release-apk }}
            # ${{ steps.set_outputs.outputs.release-ipa }}
