name: Release Actions
on:
  workflow_dispatch:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+-*"]
jobs:
  release:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Check Tag
        id: get_tag_version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: yarn install
        run: yarn install

      - if: contains(steps.get_tag_version.outputs.tag,'dev')
        run: yarn env:dev

      - if: contains(steps.get_tag_version.outputs.tag,'qa')
        run: yarn env:qa

      - if: contains(steps.get_tag_version.outputs.tag,'stag')
        run: yarn env:stag

      - if: contains(steps.get_tag_version.outputs.tag,'prod')
        run: yarn env:prod

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.BUILD_CERTIFICATE_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      # - name: Make iOS Release
      #   run: yarn releaseIOS

      - name: Make Android Release
        run: yarn releaseApk

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release-apk
      #     path: android/app/build/outputs/apk/release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: ${{steps.get_tag_version.outputs.tag}}
          files: |
            android/**/*.apk
